# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MiniGitClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'Kingfisher'
  # Pods for MiniGitClient

  target 'MiniGitClientTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

  target 'MiniGitClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
