# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MiniGitClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 3.5'
  pod 'Kingfisher', '~> 3.10'
  # Pods for MiniGitClient

  target 'MiniGitClientTests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.1'
    pod 'Nimble', '~> 7.0'
  end

  target 'MiniGitClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
